services:
  back-front-express:
    build:
      dockerfile: Dockerfile-frontback
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/hadsagono
      - GROQ_KEY_1=${GROQ_KEY_1}
      - PORT=${PORT}
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - public
      - internal

  database:
    image: mongo:4.4.29
    volumes:
      - ./mongodata:/data/db
      - ./db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hadsagono
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --auth --port 27017
    restart: unless-stopped
    networks:
      - internal

networks:
  public:
    driver: bridge
    internal: false
  internal:
    driver: bridge
    internal: true